### ISSUE TITLE
Using of is-number makes library slow

### ISSUE THREAD

**Issue by mad-gooze** [gm758/fast-median#1]
Hi!

I profiled my code which was using `fast-median` and noticed that checking for only numbers in input array eats a lot of CPU time. Perhaps you should allow calling `median` without force check (to skip it if I know what am I doing)?

**Comment by mad-gooze** [comment]
I made a [fork](https://github.com/mad-gooze/fast-median) with a parameter to disable force checking of arguments. I've also added a small [benchmark](https://github.com/mad-gooze/fast-median/blob/master/bench.js) to illustrate the issue:
```
with force check: 6050.613ms
without force check: 3007.193ms
```
As you can see, performance grows twice!

**Comment by mad-gooze** [comment]
Perhaps, the same thing should be also done in [kth-smallest](https://github.com/griffinmichl/kth-smallest) package as `is-number` eats a lot of CPU there too.

**Comment by griffinmichl** [comment]
Good call! If you want to make a PR, feel free. Otherwise I'll try to make the change in kth-smallest as well soon.

**Comment by griffinmichl** [comment]
Closing out this issue after merging #2.
